
name: Development-CI
on:
  workflow_dispatch:


jobs:
 Build-Push-To-GCR:

    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      HOSTNAME: gcr.io 
      PROJECT_ID: banded-lexicon-360413
    steps:
    
      - uses: actions/checkout@v2


      # Configure Workload Identity Federation via a credentials file.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/334782020989/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'checkanthos@banded-lexicon-360413.iam.gserviceaccount.com'

      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'


      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker banded-lexicon-360413 --quiet

      - name: build docker image
        run: |
          docker pull gcr.io/banded-lexicon-360413/asm-ready/loadgen:v0.0.1
        
      - name: build docker image
        run: |
          docker images
