
name: Development-CI
on:
  workflow_dispatch:


jobs:
 Build-Push-To-GCR:

    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      HOSTNAME: gcr.io 
      PROJECT_ID: banded-lexicon-360413
    steps:
    
      - uses: actions/checkout@v2


      # Configure Workload Identity Federation via a credentials file.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/218764890840/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@atomic-bird-377312.iam.gserviceaccount.com'

      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'


      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker atomic-bird-377312 --quiet

      - name: build docker image
        run: |
          cd customer-service
          docker build -t gcr.io/atomic-bird-377312/customer-service:1.0.0 .
          
      - name: Docker Image to Container Registry (GCR)
        run: docker push gcr.io/atomic-bird-377312/customer-service:1.0.0 
          
      - name: build docker image
        run: |
          docker images
